# Generated by Django 6.0.2 on 2026-04-14 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('enrollment_no', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('hostel_block', models.CharField(max_length=50)),
                ('room_number', models.IntegerField()),
                ('student_mobile', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('parent_mobile', models.CharField(max_length=10)),
                ('parent_email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=10)),
                ('student_contact', models.CharField(max_length=15)),
                ('student_email', models.EmailField(max_length=254)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_phone', models.CharField(max_length=15)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('travel_mode', models.CharField(max_length=20)),
                ('leave_address', models.TextField()),
                ('city_state_pin', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
